# data config
train_dir: "data/Aircraft/train"
test_dir: "data/Aircraft/test"
num_class: 100

# model config
batch_size: 16
learning_rate: 0.001
momentum: 0.9
weight_decay: 5e-4
num_epoch: 100
resize_size: 448
crop_size: 448

# visualizer config
vis_host: "http://localhost"
vis_port: 8097